import re
import urllib.parse
import wikipedia
from duckduckgo_search import DDGS

def process_image_tags(text: str) -> str:
    """
    Process [SHOW_IMAGE: query] tags in text and replace with HTML image tags.
    Strategy:
    1. DuckDuckGo Search (High quality, real images)
    2. Wikipedia (Educational content)
    3. Pollinations.ai (AI generated fallback)
    4. Google Search Link (Last resort)
    """
    if not text:
        return text
        
    if "[SHOW_IMAGE:" not in text:
        return text

    processed_text = text
    
    while True:
        match = re.search(r'\[SHOW_IMAGE:(.*?)\]', processed_text)
        if not match:
            break
            
        query = match.group(1).strip()
        print(f"🖼️ Processing image request for: {query}")
        replacement = None
        
        # 1. Try DuckDuckGo Search
        try:
            print(f"  Attempting DuckDuckGo for: {query}")
            with DDGS() as ddgs:
                results = list(ddgs.images(query, max_results=1))
                
            if results and results[0].get('image'):
                img_url = results[0]['image']
                print(f"  ✅ Found via DuckDuckGo")
                replacement = f'<br/><img src="{img_url}" alt="{query}" style="max-width: 100%; border-radius: 12px; margin-top: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" /><br/>'
        except Exception as e:
            print(f"  ⚠️ DuckDuckGo failed: {e}")

        # 2. Try Wikipedia if no result yet
        if not replacement:
            try:
                print(f"  Attempting Wikipedia for: {query}")
                wiki_results = wikipedia.search(query, results=1)
                if wiki_results:
                    page = wikipedia.page(wiki_results[0], auto_suggest=False)
                    found_wiki_image = None
                    for img_url in page.images:
                        if img_url.lower().endswith(('.jpg', '.jpeg', '.png')) and not any(x in img_url.lower() for x in ['icon', 'logo', 'symbol']):
                            found_wiki_image = img_url
                            break
                    
                    if found_wiki_image:
                        print(f"  ✅ Found via Wikipedia: {found_wiki_image}")
                        replacement = (
                            f'<br/><div style="text-align: center;">'
                            f'<img src="{found_wiki_image}" alt="{query}" style="max-width: 100%; border-radius: 12px; margin-top: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" />'
                            f'<p style="font-size: 10px; color: #666; margin-top: 4px;">Source: Wikipedia ({page.title})</p>'
                            f'</div><br/>'
                        )
            except Exception as e:
                print(f"  ⚠️ Wikipedia failed: {e}")

        # 3. Try Pollinations.ai if no result yet
        if not replacement:
            try:
                print(f"  Attempting Pollinations.ai for: {query}")
                encoded_query = urllib.parse.quote(query)
                pollinations_url = f"https://image.pollinations.ai/prompt/{encoded_query}"
                # Pollinations generates on the fly, so we assume it works if we can construct the URL.
                # It doesn't throw not found errors typically, it just makes an image.
                print(f"  ✅ Using Pollinations.ai generation")
                replacement = (
                    f'<br/><div style="text-align: center;">'
                    f'<img src="{pollinations_url}" alt="{query} (AI Generated)" style="max-width: 100%; border-radius: 12px; margin-top: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" />'
                    f'<p style="font-size: 10px; color: #666; margin-top: 4px;">Generated by AI</p>'
                    f'</div><br/>'
                )
            except Exception as e:
                print(f"  ⚠️ Pollinations failed: {e}")

        # 4. Last Resort: Google Search Link
        if not replacement:
            print(f"  Returning fallback link for: {query}")
            fallback_url = f"https://www.google.com/search?tbm=isch&q={urllib.parse.quote(query)}"
            replacement = (
                f'<div style="margin-top: 10px; padding: 10px; background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px;">'
                f'ℹ️ Unable to load preview. '
                f'<a href="{fallback_url}" target="_blank" style="color: #0284c7; text-decoration: underline; font-weight: bold;">'
                f'Click here to view images of "{query}"'
                f'</a>'
                f'</div>'
            )
            
        processed_text = processed_text.replace(match.group(0), replacement)
        
    return processed_text
